import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.

*/
/**
 *
 * @author ranoj
 */
public class flightstatus extends javax.swing.JInternalFrame {
    /**
     * Creates new form flightstatus
     */
    public flightstatus() {
        initComponents();
        autoID();
    }

    Connection con;
    PreparedStatement pst;
    ButtonGroup b1 = new ButtonGroup();

    public void autoID() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select MAX(id) from flight");
            rs.next();

            rs.getString("MAX(id)");
            if (rs.getString("MAX(id)") == null) {
                txtflightid.setText("FO001");
            } else {
                long id = Long.parseLong(rs.getString("MAX(id)").substring(2, rs.getString("MAX(id)").length()));
                id++;
                txtflightid.setText("FO" + String.format("%03d", id));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtflightname = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        txtarrtime = new javax.swing.JTextField();
        txtcharge = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtflightid = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtsource = new javax.swing.JTextField();
        txtdestination = new javax.swing.JTextField();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Flight ID");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Flight Name");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Source");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destination");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date");
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time");
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Arrival Time");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Charge");
        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Status");
        txtflightid.setText("FO");
        jButton3.setText("Find");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        txtsource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsourceMouseClicked(evt);
            }
        });
        txtdestination.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdestinationMouseClicked(evt);
            }
        });
        b1.add(r2);
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("Booked");

        b1.add(r1);
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("Not Booked");
        b1.add(r3);
        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("Delayed");
        b1.add(r4);
        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.setText("Cancelled");
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()

                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                153,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                jPanel1Layout.createSequentialGroup()

                                                                        .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)

                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jLabel4))
                                                                        .addGap(73, 73, 73)

                                                                        .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(txtflightname)
                                                                                .addComponent(txtsource)
                                                                                .addComponent(txtdestination))))
                                                .addGap(55, 55, 55))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(38, 38, 38)
                                                .addComponent(txtflightid, javax.swing.GroupLayout.PREFERRED_SIZE, 196,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel8)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(84, 84, 84)

                                                .addComponent(txtdate, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(99, 99, 99)

                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(r1)
                                                        .addComponent(r2)
                                                        .addComponent(r3)
                                                        .addComponent(r4)

                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(txtarrtime,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 223,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(txttime)
                                                                .addComponent(txtcharge,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jButton2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 129,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(96, Short.MAX_VALUE)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel5)

                                                .addComponent(txtflightid, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton3))
                                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel6)
                                        .addComponent(txtflightname, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7)
                                        .addComponent(txtarrtime, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtsource, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel8)
                                        .addComponent(txtcharge, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtdestination, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()

                                                .addGap(58, 58, 58)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79,
                                                        Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(r1)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(r2)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(r3)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(r4)))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()

                                .addGap(21, 21, 21)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(40, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(79, Short.MAX_VALUE)));
        pack();
    }// </editor-fold>

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
 // TODO add your handling code here:
 
 String id=txtflightid.getText();
 String flightname=txtflightname.getText();
 String source=txtsource.getText();

 String destination=txtdestination.getText();
 DateFormat da=new SimpleDateFormat("yyy-MM-dd");
 String date = da.format(txtdate.getDate());
 
 String depart=txttime.getText();
 String arrtime=txtarrtime.getText();
 String flightcharge=txtcharge.getText();
 String flightstatus="";
 if(r1.isSelected())
 {
 flightstatus="Not Booked";
 }
 else if(r2.isSelected())
 {
 flightstatus="Booked";
 }
 else if(r3.isSelected())
 {
 flightstatus="Delayed";
 }
 else if(r4.isSelected())
 {
 flightstatus="Cancelled";
 }
 int flag=0;
 for(int i=0;i<flightcharge.length();i++)
 {

 char c=flightcharge.charAt(i);
 if(Character.isDigit(c)==false)
 {
 JOptionPane.showMessageDialog(null,"INVALID ENTRY-The charge should ONLY be in digits!");
 txtcharge.setText("");
 txtcharge.requestFocus();
 flag=1;
 break;
 }
 }
 if(flag==0){
 
 try {
 Class.forName("com.mysql.cj.jdbc.Driver");
 con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
 pst = con.prepareStatement("update flight set 
flightname=?,source=?,destination=?,date=?,time=?,arrtime=?,flightcharge=?,status=? where id=?");
 
 pst.setString(1,flightname);
 pst.setString(2,source);
 pst.setString(3,destination);
 pst.setString(4,date);
 pst.setString(5,depart);
 pst.setString(6,arrtime);
 pst.setString(7,flightcharge);
 pst.setString(8,flightstatus);
 pst.setString(9,id);
 pst.executeUpdate();

 
 
 JOptionPane.showMessageDialog(null,"Flight details updated successfully....!");
 
 } catch (ClassNotFoundException ex) {
 Logger.getLogger(addflight.class.getName()).log(Level.SEVERE, null, ex);
 } catch (SQLException ex) {
 Logger.getLogger(addflight.class.getName()).log(Level.SEVERE, null, ex);
 }
 } 
 
 }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.hide();
    }

 private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { 
 // TODO add your handling code here:
 
 
 String id=txtflightid.getText();
 try {
 Class.forName("com.mysql.cj.jdbc.Driver");
 con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");

 pst=con.prepareStatement("select * from flight where id=?");
 pst.setString(1,id);
 ResultSet rs=pst.executeQuery();
 
 if(rs.next()==false)
 {
 JOptionPane.showMessageDialog(this,"Record not found");
 }
 else
 {
 String flightname=rs.getString("flightname");
 String source=rs.getString("source");
 String destination=rs.getString("destination");
 String date=rs.getString("date");
 String time=rs.getString("time");
 String arrtime=rs.getString("arrtime");
 String flightcharge=rs.getString("flightcharge");
 String status=rs.getString("status");
 Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(date);
 String flightstatus=rs.getString("status");
 if(flightstatus.equals("Not Booked"))
 {
 r1.setSelected(true);
 r2.setSelected(false);
 r3.setSelected(false);
 r4.setSelected(false);
 }

 else if(flightstatus.equals("Booked"))
 {
 r1.setSelected(false);
 r2.setSelected(true);
 r3.setSelected(false);
 r4.setSelected(false);
 }
 else if(flightstatus.equals("Delayed"))
 {
 r1.setSelected(false);
 r2.setSelected(false);
 r3.setSelected(true);
 r4.setSelected(false);
 }
 else if(flightstatus.equals("Cancelled"))
 {
 r1.setSelected(false);
 r2.setSelected(false);
 r3.setSelected(false);
 r4.setSelected(true);
 JOptionPane.showMessageDialog(this,"This flight was cancelled! Refund will be generated 
within 24 hours, if the flight is not re-scheduled!"); 
 }
 
 
 txtflightname.setText(flightname.trim());
 txtsource.setText(source.trim());
 txtsource.setEditable(false);

 txtdestination.setText(destination.trim());
 txtdestination.setEditable(false);
 txtdate.setDate(date1);
 txtarrtime.setText(arrtime.trim());
 txttime.setText(time.trim());
 txtcharge.setText(flightcharge.trim());
 
 } 
 
 }catch (ClassNotFoundException ex) {
 Logger.getLogger(searchAccount.class.getName()).log(Level.SEVERE, null, ex);
 } catch (SQLException ex) {
 Logger.getLogger(searchAccount.class.getName()).log(Level.SEVERE, null, ex);
 } catch (ParseException ex) {
 Logger.getLogger(searchAccount.class.getName()).log(Level.SEVERE, null, ex);
 }
 
 
 }

 private void txtsourceMouseClicked(java.awt.event.MouseEvent evt) { 
 // TODO add your handling code here:
 JOptionPane.showMessageDialog(this,"Invalid entry! You cannot change the source/destination of 
an international flight on will!");
 }

 private void txtdestinationMouseClicked(java.awt.event.MouseEvent evt) { 
 // TODO add your handling code here:

 JOptionPane.showMessageDialog(this,"Invalid entry! You cannot change the source/destination of 
an international flight on will!");
 }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JTextField txtarrtime;
    private javax.swing.JTextField txtcharge;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtdestination;
    private javax.swing.JTextField txtflightid;

    private javax.swing.JTextField txtflightname;
    private javax.swing.JTextField txtsource;
    private javax.swing.JTextField txttime;
    // End of variables declaration
}
