import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
/**
 *
 * @author ranoj
 */
public class ticket extends javax.swing.JInternalFrame {
    /**
     * Creates new form ticket
     */
    public ticket() {
        initComponents();
        autoID();
    }

    Connection con;
    PreparedStatement pst;

    public void autoID() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select MAX(id) from ticket");
            rs.next();
            rs.getString("MAX(id)");
            if (rs.getString("MAX(id)") == null) {
                txtticket.setText("TO001");
            } else {
                long id = Long.parseLong(rs.getString("MAX(id)").substring(2, rs.getString("MAX(id)").length()));
                id++;
                txtticket.setText("TO" + String.format("%03d", id));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

 /**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
 private void initComponents() {
 jPanel1 = new javax.swing.JPanel();
 txtsource = new javax.swing.JComboBox();
 txtdepart = new javax.swing.JComboBox();
 jLabel1 = new javax.swing.JLabel();
 jLabel2 = new javax.swing.JLabel();
 jButton3 = new javax.swing.JButton();
 jScrollPane1 = new javax.swing.JScrollPane();
 jTable1 = new javax.swing.JTable();
 jPanel2 = new javax.swing.JPanel();
 jLabel3 = new javax.swing.JLabel();
 txtticket = new javax.swing.JLabel();
 jPanel3 = new javax.swing.JPanel();
 jLabel5 = new javax.swing.JLabel();
 jLabel6 = new javax.swing.JLabel();
 jLabel7 = new javax.swing.JLabel();
 jLabel8 = new javax.swing.JLabel();
 txtcustid = new javax.swing.JTextField();
 txtfirstname = new javax.swing.JLabel();
 txtlastname = new javax.swing.JLabel();
 txtemail = new javax.swing.JLabel();
 jButton4 = new javax.swing.JButton();
 jPanel4 = new javax.swing.JPanel();
 jLabel12 = new javax.swing.JLabel();
 jLabel13 = new javax.swing.JLabel();
 jLabel14 = new javax.swing.JLabel();
 jLabel15 = new javax.swing.JLabel();
 jLabel16 = new javax.swing.JLabel();
 jLabel17 = new javax.swing.JLabel();
 flightno = new javax.swing.JLabel();
 flightname = new javax.swing.JLabel();
 deptime = new javax.swing.JLabel();
 txtprice = new javax.swing.JTextField();
 txtseats = new javax.swing.JSpinner();
 txtclass = new javax.swing.JComboBox();
 jButton1 = new javax.swing.JButton();
 jButton2 = new javax.swing.JButton();
 txttotal = new javax.swing.JLabel();
 jLabel4 = new javax.swing.JLabel();
 txtdate = new com.toedter.calendar.JDateChooser();
 jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Country", 
javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
 txtsource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "India", "Sri Lanka", 
"UK", "Japan", "China", "Russia", "Afghanistan", " " }));
 txtdepart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UK", "India", "Sri 
Lanka", "Japan", "China", "Russia", "Afghanistan", " " }));
 jLabel1.setText("Source");
 jLabel2.setText("Destination");
 jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
 jButton3.setText("Find flight");
 jButton3.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton3ActionPerformed(evt);
 }
 });
 javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
 jPanel1.setLayout(jPanel1Layout);
 jPanel1Layout.setHorizontalGroup(
 jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(jPanel1Layout.createSequentialGroup()
 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
 .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addGroup(jPanel1Layout.createSequentialGroup()
 
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(txtsource, javax.swing.GroupLayout.PREFERRED_SIZE, 185, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(jLabel1))
 .addGap(72, 72, 72)
 
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(jLabel2)
 .addComponent(txtdepart, javax.swing.GroupLayout.PREFERRED_SIZE, 207, 
javax.swing.GroupLayout.PREFERRED_SIZE))))
 .addGap(0, 249, Short.MAX_VALUE))
 );
 jPanel1Layout.setVerticalGroup(
 jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(jPanel1Layout.createSequentialGroup()
 .addGap(19, 19, 19)
 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel1)
 .addComponent(jLabel2))
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(txtsource, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(txtdepart, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
 .addGap(18, 18, 18)
 .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addContainerGap(33, Short.MAX_VALUE))
 );
 jTable1.setModel(new javax.swing.table.DefaultTableModel(
 new Object [][] {
 },
 new String [] {
 "Flight Number", "Flight Name", "Source", "Departure", "Date", "Dep Time", "Arr Time", 
"Charge"
 }
 ));
 jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
 public void mouseClicked(java.awt.event.MouseEvent evt) {
 jTable1MouseClicked(evt);
 }
 });
 jScrollPane1.setViewportView(jTable1);
 javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
 jPanel2.setLayout(jPanel2Layout);
 jPanel2Layout.setHorizontalGroup(
 jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGap(0, 1355, Short.MAX_VALUE)
 );
 jPanel2Layout.setVerticalGroup(
 jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGap(0, 743, Short.MAX_VALUE)
 );
 jLabel3.setText("Ticket No");
 txtticket.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
 txtticket.setForeground(new java.awt.Color(255, 0, 51));
 txtticket.setText("Ticket No");
 jLabel5.setText("CustID");
 jLabel6.setText("First Name");
 jLabel7.setText("Last Name");
 jLabel8.setText("Email");
 txtfirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 txtfirstname.setForeground(new java.awt.Color(255, 51, 51));
 txtfirstname.setText("jLabel9");
 txtlastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 txtlastname.setForeground(new java.awt.Color(255, 51, 51));
 txtlastname.setText("jLabel10");
 txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 txtemail.setForeground(new java.awt.Color(255, 51, 51));
 txtemail.setText("jLabel11");
 jButton4.setText("Search");
 jButton4.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton4ActionPerformed(evt);
 }
 });
 javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
 jPanel3.setLayout(jPanel3Layout);
 jPanel3Layout.setHorizontalGroup(
 jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(jPanel3Layout.createSequentialGroup()
 .addContainerGap()
 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

 .addComponent(jLabel5)
 .addComponent(jLabel6)
 .addComponent(jLabel7)
 .addComponent(jLabel8))
 .addGap(41, 41, 41)
 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(txtemail)
 .addComponent(txtlastname)
 .addComponent(txtfirstname)
 .addGroup(jPanel3Layout.createSequentialGroup()
 .addComponent(txtcustid, javax.swing.GroupLayout.PREFERRED_SIZE, 148, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
 .addComponent(jButton4)))
 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
 );
 jPanel3Layout.setVerticalGroup(
 jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(jPanel3Layout.createSequentialGroup()
 .addGap(29, 29, 29)
 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel5)
 .addComponent(txtcustid, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(jButton4))
 .addGap(22, 22, 22)
 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel6)
 .addComponent(txtfirstname))
 .addGap(32, 32, 32)
 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel7)
 .addComponent(txtlastname))
 .addGap(36, 36, 36)
 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel8)
 .addComponent(txtemail))
 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
 );
 jLabel12.setText("Flight No");
 jLabel13.setText("Flight Name");
 jLabel14.setText("Depart Time");
 jLabel15.setText("Class");
 jLabel16.setText("Price");
 jLabel17.setText("Seats");
 flightno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 flightno.setForeground(new java.awt.Color(255, 0, 51));
 flightno.setText("jLabel18");
 flightname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 flightname.setForeground(new java.awt.Color(255, 0, 51));
 flightname.setText("jLabel19");
 deptime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 deptime.setForeground(new java.awt.Color(255, 0, 51));
 deptime.setText("jLabel20");
 txtseats.addChangeListener(new javax.swing.event.ChangeListener() {
 public void stateChanged(javax.swing.event.ChangeEvent evt) {
 txtseatsStateChanged(evt);
 }
 });
 txtclass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economy\t", "Business\t" 
}));
 txtclass.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 txtclassActionPerformed(evt);
 }
 });
 javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
 jPanel4.setLayout(jPanel4Layout);
 jPanel4Layout.setHorizontalGroup(
 jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(jPanel4Layout.createSequentialGroup()
 .addContainerGap()
 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(jPanel4Layout.createSequentialGroup()
 
.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
 .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
 .addGap(67, 193, Short.MAX_VALUE)
 
.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(deptime, javax.swing.GroupLayout.Alignment.TRAILING)
 .addComponent(flightname, javax.swing.GroupLayout.Alignment.TRAILING)
 .addComponent(flightno, javax.swing.GroupLayout.Alignment.TRAILING)))
 .addGroup(jPanel4Layout.createSequentialGroup()
 
.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(jLabel15)
 .addComponent(jLabel16)
 .addComponent(jLabel17))
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
 
.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(txtseats, javax.swing.GroupLayout.Alignment.TRAILING, 
javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(txtclass, javax.swing.GroupLayout.Alignment.TRAILING, 
javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 
jPanel4Layout.createSequentialGroup()
 .addGap(0, 0, Short.MAX_VALUE)
 .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 128, 
javax.swing.GroupLayout.PREFERRED_SIZE))))
 );
 jPanel4Layout.setVerticalGroup(
 jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(jPanel4Layout.createSequentialGroup()
 .addGap(39, 39, 39)
 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel12)
 .addComponent(flightno))
 .addGap(34, 34, 34)
 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel13)
 .addComponent(flightname))
 .addGap(33, 33, 33)
 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel14)
 .addComponent(deptime))
 .addGap(35, 35, 35)
 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel15)
 .addComponent(txtclass, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
 .addGap(32, 32, 32)
 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel16)
 .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
 .addGap(28, 28, 28)

 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel17)
 .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
 .addContainerGap(55, Short.MAX_VALUE))
 );
 jButton1.setText("Book");
 jButton1.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton1ActionPerformed(evt);
 }
 });
 jButton2.setText("Cancel");
 jButton2.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton2ActionPerformed(evt);
 }
 });
 txttotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
 txttotal.setForeground(new java.awt.Color(255, 0, 0));
 txttotal.setText("jLabel4");
 jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
 jLabel4.setText("Final Amount =Rs.");

 javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
 getContentPane().setLayout(layout);
 layout.setHorizontalGroup(
 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()
 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()
 .addContainerGap()
 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, 
javax.swing.GroupLayout.PREFERRED_SIZE)))
 .addGroup(layout.createSequentialGroup()
 .addGap(322, 322, 322)
 .addComponent(jLabel4)
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
 .addComponent(txttotal)))
 .addGroup(layout.createSequentialGroup()
 .addGap(40, 40, 40)
 .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 493, 
Short.MAX_VALUE)
 .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, 
javax.swing.GroupLayout.PREFERRED_SIZE)))
 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()

 .addGap(18, 18, 18)
 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(txtticket)
 .addGroup(layout.createSequentialGroup()
 .addGap(26, 26, 26)
 .addComponent(jLabel3)))
 .addGap(42, 42, 42)
 .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
 .addGroup(layout.createSequentialGroup()
 .addGap(50, 50, 50)
 .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
 .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, 
javax.swing.GroupLayout.PREFERRED_SIZE)))
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
 .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
 );
 layout.setVerticalGroup(
 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()
 .addContainerGap()
 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()
 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

 .addGroup(layout.createSequentialGroup()
 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
 .addGroup(layout.createSequentialGroup()
 .addGap(60, 60, 60)
 .addComponent(jLabel3)
 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
 .addComponent(txtticket)))
 .addGap(52, 52, 52))
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 
layout.createSequentialGroup()
 .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
 .addGap(3, 3, 3)))
 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
 .addGroup(layout.createSequentialGroup()
 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(txttotal)
 .addComponent(jLabel4))
 .addGap(0, 0, Short.MAX_VALUE))
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 
layout.createSequentialGroup()
 .addGap(0, 0, Short.MAX_VALUE)
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, 
javax.swing.GroupLayout.PREFERRED_SIZE)))))
 .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
 .addGroup(layout.createSequentialGroup()
 .addGap(34, 34, 34)
 .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
 .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
 .addContainerGap(198, Short.MAX_VALUE))
 );
 pack();
 }// </editor-fold>

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String id = txtcustid.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "");
            pst = con.prepareStatement("select * from customer where id=?");
            pst.setString(1, id);
            ResultSet rs = pst.executeQuery();

            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "Record not found");
            } else {
                String fname = rs.getString("firstname");
                String lname = rs.getString("lastname");
                String email = rs.getString("emailaddress");

                txtfirstname.setText(fname.trim());
                txtlastname.setText(lname.trim());
                txtemail.setText(email.trim());

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();

        flightno.setText(Df.getValueAt(selectIndex, 0).toString());
        flightname.setText(Df.getValueAt(selectIndex, 1).toString());
        deptime.setText(Df.getValueAt(selectIndex, 5).toString());
        txtprice.setText(Df.getValueAt(selectIndex, 7).toString());

    }

    private void txtseatsStateChanged(javax.swing.event.ChangeEvent evt) {
        // TODO add your handling code here:
        int price = Integer.parseInt(txtprice.getText());
        int qty = Integer.parseInt(txtseats.getValue().toString());
        int tot = price * qty;
        txttotal.setText(String.valueOf(tot));
    }

 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
 // TODO add your handling code here:
 String ticketid=txtticket.getText();
 String flightid=flightno.getText();
 String custid=txtcustid.getText();
 String flightclass=txtclass.getSelectedItem().toString().trim();
 String price=txttotal.getText();
 String seat = txtseats.getValue().toString().trim();
 
 
 DateFormat da=new SimpleDateFormat("yyy-MM-dd");
 String date = da.format(txtdate.getDate());
 
 
 try {
 Class.forName("com.mysql.cj.jdbc.Driver");
 con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
 pst = con.prepareStatement("insert into 
ticket(id,flightid,custid,class,price,seats,date)values(?,?,?,?,?,?,?)");
 
 pst.setString(1, ticketid);
 pst.setString(2,flightid);
 pst.setString(3,custid);
 pst.setString(4,flightclass);
 pst.setString(5,price);
 pst.setString(6,seat);
 pst.setString(7,date);
 pst.executeUpdate();
 
 
 JOptionPane.showMessageDialog(null,"Booking successful!");
 
 } catch (ClassNotFoundException ex) {
 Logger.getLogger(addflight.class.getName()).log(Level.SEVERE, null, ex);
 } catch (SQLException ex) {
 Logger.getLogger(addflight.class.getName()).log(Level.SEVERE, null, ex);
 }
 
 }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.hide();
    }

 private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { 
 // TODO add your handling code here:
 String source=txtsource.getSelectedItem().toString().trim();
 String depart=txtdepart.getSelectedItem().toString().trim();
 try {
 Class.forName("com.mysql.cj.jdbc.Driver");
 con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
 pst= con.prepareStatement("select * from flight where source=? and destination=?");
 pst.setString(1,source);
 pst.setString(2,depart);
 ResultSet rs=pst.executeQuery();
 
 ResultSetMetaData rsm = rs.getMetaData();
 int c;
 c=rsm.getColumnCount();
 DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
 Df.setRowCount(0);
 

 while(rs.next())
 {
 String status=rs.getString("status");
 if(status.equals("Cancelled"))
 {
 JOptionPane.showMessageDialog(null,"WARNING-The flight chosen has been cancelled for 
the time being! We do not know when or if this flight will be re-scheduled! Please proceed with 
caution!");
 }
 Vector v2=new Vector();
 for(int i=1;i<=c;i++)
 {
 
 v2.add(rs.getString("id"));
 v2.add(rs.getString("flightname"));
 v2.add(rs.getString("source"));
 v2.add(rs.getString("destination"));
 v2.add(rs.getString("date"));
 v2.add(rs.getString("time"));
 v2.add(rs.getString("arrtime"));
 v2.add(rs.getString("flightcharge"));
 }
 Df.addRow(v2);
 }
 
 } catch (ClassNotFoundException ex) {
103
 Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
 } catch (SQLException ex) {
 Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
 }
 }

    private void txtclassActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel deptime;
    private javax.swing.JLabel flightname;
    private javax.swing.JLabel flightno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox txtclass;
    private javax.swing.JTextField txtcustid;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JComboBox txtdepart;
    private javax.swing.JLabel txtemail;
    private javax.swing.JLabel txtfirstname;
    private javax.swing.JLabel txtlastname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JSpinner txtseats;
    private javax.swing.JComboBox txtsource;
    private javax.swing.JLabel txtticket;
    private javax.swing.JLabel txttotal;
    // End of variables declaration
}
